### ISSUE TITLE
GitHub Enterprise

### ISSUE THREAD

**Issue by melodous** [nemerosa/ontrack#293]
Hi, it would be nice to have possibility connect ontrack and github enterprise server. I think the api it's the same and only changing the url should work.

**Comment by dcoraboeuf** [comment]
Hi Raul,

I do not know GitHub Enterprise, and I do not have access to it.

You can always create a Git configuration which points to the URL of a repository in GitHub Enterprise. But it wouldn't work for the access to the issues.

For my information, does GitHub Enterprise support issues the same way than GitHub?

Damien.

**Comment by melodous** [comment]
Hi Damien,

Thanks for the answer. Currently I'm not able of change github endpoint trought DSL or gui, I think ontrack expect to find your repository on https://github.com/%s. Am I losing something?

I believe Github enterprise support all the capabilities on the same way but on premises, https://enterprise.github.com/faq

**Comment by dcoraboeuf** [comment]
As of today, the GitHub end point is hard coded.

I can provide you with an additional configuration for GitHub enterprise - but not before September (holidays). Would you be able to test this? Or is there a way to have an evaluation version of GitHub enterprise?

**Comment by dcoraboeuf** [comment]
I just saw in the FAQ that I could have access to a 45-days evaluation license.

**Comment by melodous** [comment]
It'd be nice, and yes, I can test it on a  real installation.

**Comment by dcoraboeuf** [comment]
Ok, that's a deal - I can do this in September.

**Comment by dcoraboeuf** [comment]
Hi Raul, I have started to work on this feature.

I'll probably refactor the GitHub configuration in order to align it with what I've done with Stash:

* GitHub configurations (enterprise or github.com), with associated credentials
* Project configuration using a GitHub configuration + a repository name

This avoids the repetition of credentials from one repository to the other.

I'll have to write a migration process for the existing GitHub configurations.

**Comment by melodous** [comment]
OK, I'll test it when you finish.
