### ISSUE TITLE
Support for Gitlab.

### ISSUE THREAD

**Issue by daonerz** [nemerosa/ontrack#352]
Very interesting tool.
Is it possible to consider a integration with Gitlab ?

**Comment by dcoraboeuf** [comment]
Hi,

Ontrack supports already Subversion, GitHub (Cloud + Enterprise), Stash and generic Git repositories.

Using generic Git repositories would already allow you to support some repositories hosted by GitLab. Now, having a dedicated GitLab for support would of course allow for an easier management, and take advantage of the issue management aspects.

I do not think it would be that much different most what has been done already for GitHub. Since I do not have any experience on GitLab, would you be interested in contributing?

Damien.

**Comment by dcoraboeuf** [comment]
- [ ] GitLab module
- [ ] GitLab configuration
- [ ] GitLab issues - optional, can be another one

Using https://github.com/timols/java-gitlab-api as Java API client.
