### ISSUE TITLE
Reordering of Validation Stamps failed

### ISSUE THREAD

**Issue by flesire** [nemerosa/ontrack#449]
In 2.24.3, the reordering of the validation stamps does not work anymore. We can drag & drop validation stamps but when it's dropped, it's not at the correct place.

**Comment by dcoraboeuf** [comment]
I can reproduce the problem in some circumstances. But so far, I could not find any error nor establish a cause :(

**Comment by dcoraboeuf** [comment]
I can reproduce the version when the application is _packaged_ with its JS compressed and minified. So something must be wrong in the way the `angular-ui-sortable` module is dealing with variables. Since nothing has changed in this area since March 15th, is it possible that the defect exists since then?

**Comment by dcoraboeuf** [comment]
Looks awfully like angular-ui/ui-sortable#29. Investigating but upgrading to version 0.13 or 0.14 might solve the issue.

**Comment by dcoraboeuf** [comment]
Will be fixed in 2.24.4
