### ISSUE TITLE
How to fetch metadata from Validationstamps

### ISSUE THREAD

**Issue by DavidCADanneels** [nemerosa/ontrack#635]
Using the following Ontrack DSL call:
```
println "services = ${services}"
println "images = ${images}"

def allServices = services.split(',')
def allImages = images.split(',')

def size = allServices.size()

for(int i=0;i<size;i++){
  def service = allServices[i]
  def image = allImages[i]
  println "${service} = ${image}"
  ontrack.validationStamp('SPEEDBOAT','IMAGE_USAGE','CI.WLS122-JDK8-ORACLE121').config {
    metaInfo service, image
  }
}
```
I was able to provide metadata on Validation Stamps:
![ontrack-images](https://user-images.githubusercontent.com/5195271/49990960-d2f4fb00-ff7f-11e8-988e-61442855dad6.png)

Now I want to fetch that information again from Ontrack in order to add a search criterium in our Info Search Extension (CGI), but I don't find that information. I already checked the ValidationStamp object, the Run and View objects, ...

Can you point me the right direction?

**Comment by dcoraboeuf** [comment]
There is indeed a hole in the documentation (missing link), but the documentation is actually there:

http://nemerosa.github.io/ontrack/release/latest/doc/index.html#dsl-projectentityproperties

In particular, you can get the meta information on any project entity (project, branch, validation stamp, build, promotion, etc.) using the `metaInfo` property on the `config` object ; it returns a list of `MetaInfo` objects having the following properties: `name`, `value`, `link` and `category`.

So, in your case, it should look something like:

```
def validationStamp = ...
def metaInfos = validationStamp.config.metaInfos
def metaInfo = metaInfos.get(0)

metaInfo.name
metaInfo.value
metaInfo.link
metaInfo.category
```

I hope it helps. In the meantime, I'll let this ticket open because there is indeed a hole in the generated documentation.

BR
Damien

**Comment by dcoraboeuf** [comment]
⬆️ Documentation will be corrected in next 3.x release.

**Comment by DavidCADanneels** [comment]
Please note that we are using Ontrack version 2.34.6 and Java code to fetch the Validation Stamp.
I also verified your latest commit and noticed an update on the ValidationStamp.getConfig (method)
I don't see this method in the source code of our Ontrack version (2.34.6). Has this been added later?
If so, I guess we will need to upgrade our underlying Ontrack version as well.

**Comment by dcoraboeuf** [comment]
Ok, I might have misunderstood ; where are you trying to get the information from using Java code? From an extension, using Ontrack internal API?

**Comment by dcoraboeuf** [comment]
The Ontrack DSL is used for remote access only (typically from tools or from Jenkins). If you code within an extension, you can directly access the internal API of Ontrack (2.x or 3.x, does not matter).

In your case, you want to access the `MetaInfoPropertyType` property value on the `ValidationStamp` object. Make sure you inject the `PropertyService` in your class and do something like:

```
ValidationStamp vs = ...
MetaInfoProperty property = propertyService.getProperty(vs, MetaInfoPropertyType.class).value
if (property != null) {
    property.getItems().forEach( item ->
        item.getName()
        item.getValue()
        ...
    )
}
```

Note: for the property type to be visible, make sure the General extension is available in your extension. You typically do this at Gradle level by doing:

```
ontrack {
   ...
   uses 'general'
}
```

See http://nemerosa.github.io/ontrack/release/2.35.0/doc/index.html#extending-options for more information.

If time would allow me to work on this, I'd dream of having a Kotlin-based (typed) DSL we can use at extension level.

This code will work in both 2.x and 3.x (3.x is just using Postgres instead of H2, and that's a big migration - I can consider the 2.35 version as LTS version).

**Comment by DavidCADanneels** [comment]
Ok, thanks, that _propertyService_ was my missing link. I can continue now.
I'll keep the ticket open, so you can use it for your documentation update.

**Comment by dcoraboeuf** [comment]
I can actually close the ticket - documentation has been corrected (at least for the 3.x version branch).

Thanks for the feedback and good luck.
