### ISSUE TITLE
Could not delete validation stamp

### ISSUE THREAD

**Issue by nevers** [nemerosa/ontrack#849]
Hi.

I'm getting a permission exception when trying to delete a validation stamp that I previously created.

I do see the link to remove the validation stamp (in the top right menu bar) but it shows the following exception when attempting to perform the actual remove:
![Screen Shot 2021-03-25 at 14 00 48](https://user-images.githubusercontent.com/6615923/112486647-5d8e4c80-8d7c-11eb-98c1-da3f690b5b2b.png)

Thanks

**Comment by dcoraboeuf** [comment]
* issue has been identified in the `AutoPromotionEventListener` code, which cleans out auto promotions setups throughout the project
* root cause is that a property must be edited upon the deletion of a validation stamp, but having the rights to delete a validation stamp does not give you the right to edit another property. The `AutoPromotionEventListener` must use a "sudo" mode for this edition
