### ISSUE TITLE
Is it possible to upgrade spring in 2.35.2 version ?

### ISSUE THREAD

**Issue by raj333921** [nemerosa/ontrack#853]
We are trying to upgrade JDK and seeing issues with spring lower versions.
Ontrack: 2.35.2

In our extension versions I couldnt able to update to newer spring versions.
 org.springframework.aop.framework.AopConfigException
14:26:12          Caused by: org.springframework.cglib.core.CodeGenerationException
14:26:12              Caused by: java.lang.reflect.InvocationTargetException
14:26:12                  Caused by: java.lang.ClassFormatError

**Comment by raj333921** [comment]
FROM openjdk:8u151-jdk please update to openjdk:8u282-jdk 
Thanks

**Comment by dcoraboeuf** [comment]
Hi @raj333921 ,

I don't want to keep supporting versions 2.x. Have you considered migrating to version 3.x?

Thanks,
Damien

**Comment by raj333921** [comment]
Hi @dcoraboeuf  Yes we have a plan, But for now we want to upgrade only JDK version, Please help only one change by that time we will be moving to 3.x version

**Comment by dcoraboeuf** [comment]
Latest version 2.35 uses Spring Boot 1.5.12, which is no longer supported.

Migration from Spring Boot 1.5 to version 2.1 has been done in Ontrack 3.x, and upgraded to 2.4 in Ontrack 4.x.

I don't think it is feasible to upgrade Spring Boot in Ontrack 2.x since this requires quite a lot of refactoring.
